// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrKEZS9DFE0Lk-RbnpBilO2X9fAhF_e_k',
    appId: '1:902460580589:web:6a5144def5e4a0245622e4',
    messagingSenderId: '902460580589',
    projectId: 'ysug-arcadia-dev',
    authDomain: 'ysug-arcadia-dev.firebaseapp.com',
    databaseURL: 'https://ysug-arcadia-dev-default-rtdb.firebaseio.com',
    storageBucket: 'ysug-arcadia-dev.appspot.com',
    measurementId: 'G-TGBXD0FNDF',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFgsjSRQwNfgbOmEqxNSnAgeQIGRQoa-E',
    appId: '1:902460580589:ios:6ed9f76c644864fd5622e4',
    messagingSenderId: '902460580589',
    projectId: 'ysug-arcadia-dev',
    databaseURL: 'https://ysug-arcadia-dev-default-rtdb.firebaseio.com',
    storageBucket: 'ysug-arcadia-dev.appspot.com',
    iosBundleId: 'com.ysug.arcadia',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh-7z1c4tNGVPC8f8rY_ImNFu6cqDn_Ww',
    appId: '1:902460580589:android:5b7ef4d75ee28d545622e4',
    messagingSenderId: '902460580589',
    projectId: 'ysug-arcadia-dev',
    databaseURL: 'https://ysug-arcadia-dev-default-rtdb.firebaseio.com',
    storageBucket: 'ysug-arcadia-dev.appspot.com',
  );
}
